<Project Sdk="Microsoft.NET.Sdk">



  <PropertyGroup>

    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>

  </PropertyGroup>



  <ItemGroup>

    <PackageReference Include="coverlet.collector" />

    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />

    <PackageReference Include="Microsoft.Data.SqlClient" />

    <PackageReference Include="Testcontainers" />

    <PackageReference Include="Testcontainers.MsSql" />

    <PackageReference Include="Microsoft.NET.Test.Sdk" />

    <PackageReference Include="Microsoft.OpenApi" />

    <PackageReference Include="xunit.v3" />

    <PackageReference Include="xunit.runner.visualstudio" />

  </ItemGroup>



  <ItemGroup>

    <Using Include="Xunit" />

  </ItemGroup>



  <ItemGroup>

    <ProjectReference Include="..\Shora.Application\Shora.Application.csproj" />

    <ProjectReference Include="..\Shora.Contracts\Shora.Contracts.csproj" />

    <ProjectReference Include="..\Shora.Infrastructure\Shora.Infrastructure.csproj" />

    <ProjectReference Include="..\Shora.Api\Shora.Api.csproj" />

  </ItemGroup>



</Project>

