using Shora.Application.Common.Results;

namespace Shora.Application.Common;

public sealed record ErrorCatalogEntry(
    string Code,
    int Status,
    string Title,
    string Summary,
    string? WhenItOccurs = null,
    string? RelatedEndpoint = null);

public static class ErrorCatalog
{
    private static readonly ErrorCatalogEntry[] Entries =
    [
        Entry(ErrorCodes.Auth.InvalidCredentials, ErrorKind.Unauthorized,
            "Invalid credentials",
            "Login failed because the email or password did not match an account.",
            "POST /api/v1/auth/login with wrong email or password",
            "POST /api/v1/auth/login"),
        Entry(ErrorCodes.Auth.DuplicateEmail, ErrorKind.Conflict,
            "Email is already registered",
            "A client tried to sign up with an email that already has an account.",
            "Second signup with the same email address",
            "POST /api/v1/auth/signup"),
        Entry(ErrorCodes.Auth.RefreshTokenMissing, ErrorKind.Unauthorized,
            "Refresh token missing",
            "The refresh-token cookie was not sent with the request.",
            "POST /api/v1/auth/refresh or logout without a refresh cookie",
            "POST /api/v1/auth/refresh"),
        Entry(ErrorCodes.Auth.RefreshTokenInvalid, ErrorKind.Unauthorized,
            "Refresh token invalid",
            "The refresh token is expired, revoked, or not recognized.",
            "Refresh with an expired or revoked cookie",
            "POST /api/v1/auth/refresh"),
        Entry(ErrorCodes.Auth.RefreshTokenReuse, ErrorKind.Unauthorized,
            "Refresh token reuse detected",
            "A previously rotated refresh token was presented again; all sessions were revoked.",
            "Refresh with a token revoked more than 60 seconds ago",
            "POST /api/v1/auth/refresh"),
        Entry(ErrorCodes.Auth.GoogleSignInFailed, ErrorKind.Unauthorized,
            "Google sign-in failed",
            "The Google ID token could not be validated.",
            "POST /api/v1/auth/google with an invalid or expired idToken",
            "POST /api/v1/auth/google"),
        Entry(ErrorCodes.Auth.VerificationFailed, ErrorKind.Validation,
            "Email verification failed",
            "The verification link is invalid, expired, or the user was not found.",
            "GET verify-email with bad token or unknown email",
            "POST /api/v1/auth/verify-email"),
        Entry(ErrorCodes.Auth.ResetFailed, ErrorKind.Validation,
            "Password reset failed",
            "The reset token is invalid or the password did not meet policy.",
            "POST /api/v1/auth/reset-password with bad token",
            "POST /api/v1/auth/reset-password"),
        Entry(ErrorCodes.Auth.UserNotFound, ErrorKind.NotFound,
            "User not found",
            "No user exists for the requested identifier.",
            "Authenticated action targets a missing user",
            null),
        Entry(ErrorCodes.Auth.ValidationFailed, ErrorKind.Validation,
            "Auth validation failed",
            "Identity validation failed (for example password policy).",
            "Signup or password change with invalid fields",
            "POST /api/v1/auth/signup"),
        Entry(ErrorCodes.Settings.NotFound, ErrorKind.NotFound,
            "Settings not found",
            "The singleton settings row has not been seeded yet.",
            "Booking or admin flow before settings exist",
            "GET /api/v1/settings/public"),
        Entry(ErrorCodes.Availability.InvalidRange, ErrorKind.Validation,
            "Invalid availability range",
            "The from/to query parameters are missing or from is after to.",
            "GET /api/v1/availability with invalid range",
            "GET /api/v1/availability"),
        Entry(ErrorCodes.Availability.RangeTooLarge, ErrorKind.Validation,
            "Availability range too large",
            "The requested availability window exceeds the allowed span.",
            "GET /api/v1/availability with an oversized range",
            "GET /api/v1/availability"),
        Entry(ErrorCodes.Availability.WindowNotFound, ErrorKind.NotFound,
            "Availability window not found",
            "The admin availability window id does not exist.",
            "Admin updates or deletes a missing window",
            "PUT /api/v1/admin/availability/windows/{id}"),
        Entry(ErrorCodes.Availability.BlockedDateNotFound, ErrorKind.NotFound,
            "Blocked date not found",
            "The blocked-date id does not exist.",
            "Admin deletes a missing blocked date",
            "DELETE /api/v1/admin/blocked-dates/{id}"),
        Entry(ErrorCodes.Availability.BlockedRangeConflictsWithBookings, ErrorKind.Conflict,
            "Blocked range conflicts with bookings",
            "Active bookings overlap the requested blocked range.",
            "Admin creates a block that covers booked slots",
            "POST /api/v1/admin/blocked-dates"),
        Entry(ErrorCodes.Booking.SlotUnavailable, ErrorKind.Conflict,
            "Slot unavailable",
            "The selected slot is no longer free to reserve.",
            "Reserve or create booking for a taken or expired slot",
            "POST /api/v1/bookings/reserve"),
        Entry(ErrorCodes.Booking.HoldCapExceeded, ErrorKind.Conflict,
            "Hold cap exceeded",
            "The client already holds the maximum number of unconfirmed bookings.",
            "Reserve when unconfirmed hold limit is reached",
            "POST /api/v1/bookings/reserve"),
        Entry(ErrorCodes.Booking.EmailNotVerified, ErrorKind.Forbidden,
            "Email not verified",
            "The account must verify email before booking.",
            "Reserve or create booking with EmailConfirmed false",
            "POST /api/v1/bookings/reserve"),
        Entry(ErrorCodes.Booking.ContactPhoneRequired, ErrorKind.Validation,
            "Contact phone required",
            "Voice-call bookings require a contact phone number.",
            "Create booking with VoiceCall and no contactPhone",
            "POST /api/v1/bookings"),
        Entry(ErrorCodes.Booking.ContactPhoneInvalid, ErrorKind.Validation,
            "Contact phone invalid",
            "The contact phone format is not accepted.",
            "Create booking with malformed contactPhone",
            "POST /api/v1/bookings"),
        Entry(ErrorCodes.Booking.NotFound, ErrorKind.NotFound,
            "Booking not found",
            "No booking exists for the requested id.",
            "Client or admin action on missing booking",
            "GET /api/v1/bookings/{id}"),
        Entry(ErrorCodes.Booking.Forbidden, ErrorKind.Forbidden,
            "Booking access forbidden",
            "The authenticated user may not access this booking.",
            "Client accesses another user's booking",
            "GET /api/v1/bookings/{id}"),
        Entry(ErrorCodes.Booking.InvalidStatus, ErrorKind.Conflict,
            "Invalid booking status",
            "The booking is not in the status required for this action.",
            "Cancel, pay, or admin action on wrong booking state",
            "POST /api/v1/bookings/{id}/cancel-request"),
        Entry(ErrorCodes.Cancellation.TooLate, ErrorKind.Conflict,
            "Cancellation too late",
            "The cancellation window for this booking has passed.",
            "Client requests cancellation after the allowed deadline",
            "POST /api/v1/bookings/{id}/cancel-request"),
        Entry(ErrorCodes.Cancellation.ReopenExhausted, ErrorKind.Conflict,
            "Cancellation reopen exhausted",
            "The booking cannot be reopened for cancellation again.",
            "Client reopens cancellation after limit",
            "POST /api/v1/bookings/{id}/reopen-cancellation"),
        Entry(ErrorCodes.Cancellation.InvalidDecisionReason, ErrorKind.Validation,
            "Invalid cancellation decision reason",
            "The admin decline reason code is not allowed.",
            "Admin declines cancellation with invalid reason",
            "POST /api/v1/admin/bookings/{id}/cancellation/decide"),
        Entry(ErrorCodes.Payment.NotFound, ErrorKind.NotFound,
            "Payment not found",
            "No payment record exists for the booking.",
            "Receipt upload or admin review without payment row",
            "GET /api/v1/bookings/{id}/payment-instructions"),
        Entry(ErrorCodes.Payment.Forbidden, ErrorKind.Forbidden,
            "Payment access forbidden",
            "The user may not access this payment.",
            "Unauthorized payment or receipt access",
            "POST /api/v1/payments/receipts"),
        Entry(ErrorCodes.Payment.InvalidStatus, ErrorKind.Conflict,
            "Invalid payment status",
            "The payment is not in the status required for this action.",
            "Upload receipt or admin review at wrong payment state",
            "POST /api/v1/payments/receipts"),
        Entry(ErrorCodes.Payment.UploadDeadlinePassed, ErrorKind.Conflict,
            "Receipt upload deadline passed",
            "The window to upload a receipt for this booking has closed.",
            "Client uploads after deadline",
            "POST /api/v1/payments/receipts"),
        Entry(ErrorCodes.Payment.InvalidReceiptFile, ErrorKind.Validation,
            "Invalid receipt file",
            "The uploaded file is not an allowed receipt type.",
            "Upload non-image or corrupt file",
            "POST /api/v1/payments/receipts"),
        Entry(ErrorCodes.Payment.ReceiptTooLarge, ErrorKind.PayloadTooLarge,
            "Receipt too large",
            "The uploaded receipt exceeds the maximum file size.",
            "Upload file above ReceiptUpload:MaxSizeBytes",
            "POST /api/v1/payments/receipts"),
        Entry(ErrorCodes.Payment.InvalidMethod, ErrorKind.Validation,
            "Invalid payment method",
            "The selected manual payment method is not supported.",
            "Reserve with unknown payment method",
            "POST /api/v1/bookings/reserve"),
        Entry(ErrorCodes.Payment.NoPendingReceipt, ErrorKind.Conflict,
            "No pending receipt",
            "There is no receipt awaiting admin review.",
            "Admin approves or declines when none is pending",
            "POST /api/v1/admin/receipts/{bookingId}/approve"),
        Entry(ErrorCodes.Payment.ReceiptFinalizeFailed, ErrorKind.Failure,
            "Receipt finalize failed",
            "Blob storage or persistence failed while saving the receipt.",
            "Upload succeeds in validation but storage write fails",
            "POST /api/v1/payments/receipts"),
        Entry(ErrorCodes.Payment.ReceiptNotReviewable, ErrorKind.Conflict,
            "Receipt not reviewable",
            "The receipt cannot be reviewed in its current state.",
            "Admin review on wrong receipt state",
            "POST /api/v1/admin/receipts/{bookingId}/approve"),
        Entry(ErrorCodes.Payment.InvalidDeclineReason, ErrorKind.Validation,
            "Invalid receipt decline reason",
            "The decline reason code is not allowed.",
            "Admin declines receipt with invalid reason",
            "POST /api/v1/admin/receipts/{bookingId}/decline"),
        Entry(ErrorCodes.Payment.RefundNotDue, ErrorKind.Conflict,
            "Refund not due",
            "The payment is not eligible to be marked refunded.",
            "Admin records refund before conditions are met",
            "POST /api/v1/admin/refunds"),
        Entry(ErrorCodes.Payment.NotRefunded, ErrorKind.Conflict,
            "Payment not refunded",
            "The payment was not in refunded status for revocation.",
            "Admin revokes refund on non-refunded payment",
            "POST /api/v1/admin/refunds/{paymentId}/revoke"),
        Entry(ErrorCodes.Payment.InvalidRefundReference, ErrorKind.Validation,
            "Invalid refund reference",
            "The refund reference field failed validation.",
            "Admin records refund with invalid reference",
            "POST /api/v1/admin/refunds"),
        Entry(ErrorCodes.Payment.InvalidRefundRevocationReason, ErrorKind.Validation,
            "Invalid refund revocation reason",
            "The refund revocation reason is not allowed.",
            "Admin revokes refund with invalid reason",
            "POST /api/v1/admin/refunds/{paymentId}/revoke"),
        Entry(ErrorCodes.General.Validation, ErrorKind.Validation,
            "Validation error",
            "One or more request fields failed validation.",
            "Model binding or business validation failure",
            null),
        Entry(ErrorCodes.General.Unexpected, ErrorKind.Failure,
            "Unexpected error",
            "An unhandled server error occurred.",
            "Unhandled exception in the pipeline",
            null),
        Entry(ErrorCodes.General.Forbidden, ErrorKind.Forbidden,
            "Forbidden",
            "The caller is not allowed to perform this action.",
            "Missing role or policy failure",
            null),
        Entry(ErrorCodes.Errors.NotFound, ErrorKind.NotFound,
            "Error code not found",
            "The requested error catalog code does not exist.",
            "GET /api/v1/errors/{code} with unknown code",
            "GET /api/v1/errors/{code}"),
    ];

    private static readonly IReadOnlyDictionary<string, ErrorCatalogEntry> ByCode =
        Entries.ToDictionary(e => e.Code, StringComparer.Ordinal);

    public static IReadOnlyList<ErrorCatalogEntry> All { get; } = Entries;

    public static IReadOnlyDictionary<string, IReadOnlyList<ErrorCatalogEntry>> ByCategory { get; } =
        Entries
            .GroupBy(e => e.Code.Split('.')[0], StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => (IReadOnlyList<ErrorCatalogEntry>)g.ToList(), StringComparer.Ordinal);

    public static ErrorCatalogEntry? TryGet(string code) =>
        ByCode.TryGetValue(code, out var entry) ? entry : null;

    private static ErrorCatalogEntry Entry(
        string code,
        ErrorKind kind,
        string title,
        string summary,
        string? whenItOccurs,
        string? relatedEndpoint) =>
        new(code, (int)kind, title, summary, whenItOccurs, relatedEndpoint);
}
